GRANT USAGE ON SCHEMA public TO sparky;
GRANT CREATE ON SCHEMA public TO sparky;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sparky;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sparky;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO sparky;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO sparky;
SELECT 'OK' AS resultat;
